# Generated by Django 3.0.5 on 2020-05-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailactivation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailActivation',
        ),
    ]
