# Generated by Django 3.0.5 on 2020-04-26 06:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_ebook_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebook',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_ebook_path),
        ),
    ]
