# Generated by Django 3.0.5 on 2020-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200506_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
