# Generated by Django 3.0.5 on 2020-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_products'),
        ('products', '0009_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
