# Generated by Django 3.0.5 on 2020-05-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('products', '0011_product_time_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
